//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        public int id { get; set; }
       // [DataType("text")]
       // [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Name can contain only alphabets")]
        public string name { get; set; }
        public System.DateTime date { get; set; }
      //  [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$",
       //    ErrorMessage = "E-mail is not valid")]
        public string email { get; set; }
      //  [RegularExpression(@"^([0-9]{10})$", ErrorMessage = "Invalid Mobile Number.")]
        public long mobile { get; set; }
        public string copyOfId { get; set; }
        public string uniqueID { get; set; }
        public int balance { get; set; }
    }
}
